services:
  # MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    container_name: hanainplan-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./datacode.sql:/docker-entrypoint-initdb.d/02-datacode.sql
    networks:
      - hanainplan-network
    restart: unless-stopped

  # Redis 캐시 및 세션 스토어
  redis:
    image: redis:7-alpine
    container_name: hanainplan-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - hanainplan-network
    restart: unless-stopped

  # MongoDB 문서 데이터베이스
  mongodb:
    image: mongo:6.0
    container_name: hanainplan-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb/init.js:/docker-entrypoint-initdb.d/init.js
    networks:
      - hanainplan-network
    restart: unless-stopped

  # Spring Boot 애플리케이션
  hanainplan-app:
    build: .
    container_name: hanainplan-spring-app
    depends_on:
      - mysql
      - redis
      - mongodb
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: ${MONGO_DATABASE}
      MONGODB_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGODB_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - hanainplan-network
    restart: unless-stopped

  # 관리 도구들 (선택사항)

#  mongo-express:
#    image: mongo-express
#    container_name: hanainplan-mongo-express
#    depends_on:
#      - mongodb
#    ports:
#      - "8082:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
#      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
#      ME_CONFIG_MONGODB_SERVER: mongodb
#    networks:
#      - hanainplan-network
#
#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    container_name: hanainplan-redis-commander
#    depends_on:
#      - redis
#    ports:
#      - "8083:8081"
#    environment:
#      REDIS_HOSTS: local:redis:6379
#    networks:
#      - hanainplan-network

volumes:
  mysql_data:
  redis_data:
  mongodb_data:

networks:
  hanainplan-network:
    driver: bridge