version: '3.8'

services:
  hanhwa-insurance-mysql:
    image: mysql:8.0
    container_name: hanhwa-insurance-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3312:3306"
    volumes:
      - hanhwa_insurance_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  hanhwa-insurance-app:
    build: .
    container_name: hanhwa-insurance-app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8092:8092"
    depends_on:
      - hanhwa-insurance-mysql
    restart: unless-stopped

volumes:
  hanhwa_insurance_data:
