spring:
  profiles:
    active: local

  application:
    name: hanainplan

server:
  port: 8080

logging:
  level:
    com.hanainplan: DEBUG
    org.springframework.web: DEBUG

# 카카오 OAuth 설정
kakao:
  restapi:
    key: ${KAKAO_RESTAPI_KEY}
  redirect:
    uri: http://localhost:5173/auth/kakao/callback