server:
  port: 8084

spring:
  application:
    name: user-server
  
  datasource:
    url: jdbc:mysql://localhost:3310/user_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

logging:
  level:
    com.hanainplan.user: DEBUG
    org.springframework.web: DEBUG

# Swagger 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true
