version: '3.8'

services:
  hana-insurance-mysql:
    image: mysql:8.0
    container_name: hana-insurance-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3311:3306"
    volumes:
      - hana_insurance_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  hana-insurance-app:
    build: .
    container_name: hana-insurance-app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8091:8091"
    depends_on:
      - hana-insurance-mysql
    restart: unless-stopped

volumes:
  hana_insurance_data:
